package com.guard.notifyguard

import androidx.compose.runtime.staticCompositionLocalOf

enum class Lang { SYSTEM, RU, EN }

/**
 * Тексты интерфейса. Держим их в коде, а не в ресурсах:
 * так язык переключается мгновенно, без пересоздания активности.
 */
data class Strings(
    val appTitle: String,
    val logTitle: String,
    val back: String,

    val accessTitle: String,
    val accessNotifications: String,
    val accessNotificationsOn: String,
    val accessNotificationsOff: String,
    val accessCalls: String,
    val accessCallsOn: String,
    val accessCallsOff: String,
    val accessContacts: String,
    val accessContactsOn: String,
    val accessContactsOff: String,
    val actionOpenSettings: String,
    val actionAssign: String,
    val actionGrant: String,
    val enabled: String,
    val disabled: String,

    val notificationsTitle: String,
    val hideAds: String,
    val hideAdsHint: String,
    val strictMode: String,
    val strictModeHint: String,
    val whitelistCount: String,
    val chooseApps: String,

    val stopWordsTitle: String,
    val stopWordsHint: String,
    val stopWordsPlaceholder: String,
    val allowWordsTitle: String,
    val allowWordsHint: String,
    val allowWordsPlaceholder: String,
    val add: String,
    val remove: String,
    val emptyList: String,
    val wordMatchHint: String,

    val callsTitle: String,
    val silenceUnknown: String,
    val silenceUnknownHint: String,
    val callsWarning: String,

    val appearanceTitle: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val langSystem: String,
    val langRu: String,
    val langEn: String,

    val privacyTitle: String,
    val storeText: String,
    val storeTextHint: String,

    val openLog: String,
    val openLogHint: String,
    val tabNotifications: String,
    val tabCalls: String,
    val clear: String,
    val emptyNotifications: String,
    val emptyCalls: String,
    val unwhitelist: String,
    val hiddenText: String,
    val silenced: String,
    val allowedCall: String,

    val pickerTitle: String,
    val pickerHint: String,
    val pickerEmpty: String,
    val search: String,
    val done: String
)

val RU = Strings(
    appTitle = "Тихие уведомления",
    logTitle = "Журнал",
    back = "Назад",

    accessTitle = "Доступ",
    accessNotifications = "Чтение уведомлений",
    accessNotificationsOn = "Фильтр может снимать уведомления",
    accessNotificationsOff = "Без этого доступа фильтр не работает",
    accessCalls = "Проверка звонков",
    accessCallsOn = "Можно приглушать незнакомые номера",
    accessCallsOff = "Нужно, чтобы приглушать звонки",
    accessContacts = "Доступ к контактам",
    accessContactsOn = "Знакомые номера звонят как обычно",
    accessContactsOff = "Без контактов все номера считаются знакомыми",
    actionOpenSettings = "Настройки",
    actionAssign = "Назначить",
    actionGrant = "Разрешить",
    enabled = "включено",
    disabled = "выключено",

    notificationsTitle = "Уведомления",
    hideAds = "Скрывать рекламу",
    hideAdsHint = "Коды, операции по счёту, личные сообщения, статусы доставки и экстренные оповещения остаются",
    strictMode = "Строгий режим",
    strictModeHint = "Показывать только белый список, коды и переводы",
    whitelistCount = "Белый список",
    chooseApps = "Выбрать приложения",

    stopWordsTitle = "Стоп-слова",
    stopWordsHint = "Уведомление с таким словом скрывается, даже если в нём есть сумма или слово «код». Экстренные оповещения и состояние устройства не перекрываются.",
    stopWordsPlaceholder = "например: кредит",
    allowWordsTitle = "Слова-исключения",
    allowWordsHint = "Уведомление с таким словом не скрывается никогда.",
    allowWordsPlaceholder = "например: сбербанк",
    add = "Добавить",
    remove = "Удалить",
    emptyList = "Список пуст",
    wordMatchHint = "Слово ищется по началу: «кредит» поймает «кредиты», но не сработает внутри другого слова.",

    callsTitle = "Звонки",
    silenceUnknown = "Приглушать незнакомые номера",
    silenceUnknownHint = "Звонок не из контактов проходит без звука, но остаётся в журнале вызовов",
    callsWarning = "Назначьте приложение для проверки звонков, иначе настройка ни на что не влияет",

    appearanceTitle = "Оформление",
    theme = "Тема",
    themeSystem = "Как в системе",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    language = "Язык",
    langSystem = "Системный",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Приватность",
    storeText = "Сохранять текст в журнале",
    storeTextHint = "Выключите, если не хотите, чтобы тексты уведомлений хранились на устройстве",

    openLog = "Журнал",
    openLogHint = "Скрытые уведомления и приглушённые звонки",
    tabNotifications = "Уведомления",
    tabCalls = "Звонки",
    clear = "Очистить",
    emptyNotifications = "Пока ничего не скрыто",
    emptyCalls = "Приглушённых звонков не было",
    unwhitelist = "Больше не скрывать это приложение",
    hiddenText = "текст не сохранён",
    silenced = "приглушён",
    allowedCall = "пропущен со звуком",

    pickerTitle = "Всегда показывать",
    pickerHint = "Список пополняется по мере того, как приложения присылают уведомления",
    pickerEmpty = "Приложения появятся здесь после первых уведомлений",
    search = "Поиск",
    done = "Готово"
)

val EN = Strings(
    appTitle = "Quiet Notifications",
    logTitle = "Log",
    back = "Back",

    accessTitle = "Access",
    accessNotifications = "Notification access",
    accessNotificationsOn = "The filter can dismiss notifications",
    accessNotificationsOff = "The filter does nothing without this",
    accessCalls = "Call screening",
    accessCallsOn = "Unknown numbers can be silenced",
    accessCallsOff = "Required to silence calls",
    accessContacts = "Contacts access",
    accessContactsOn = "Known numbers ring normally",
    accessContactsOff = "Without contacts every number counts as known",
    actionOpenSettings = "Settings",
    actionAssign = "Assign",
    actionGrant = "Grant",
    enabled = "on",
    disabled = "off",

    notificationsTitle = "Notifications",
    hideAds = "Hide ads",
    hideAdsHint = "Codes, account activity, personal messages, delivery updates and emergency alerts stay visible",
    strictMode = "Strict mode",
    strictModeHint = "Show only whitelisted apps, codes and transfers",
    whitelistCount = "Whitelist",
    chooseApps = "Choose apps",

    stopWordsTitle = "Blocked words",
    stopWordsHint = "A notification containing this word is hidden even if it mentions an amount or a code. Emergency alerts and device status are never overridden.",
    stopWordsPlaceholder = "e.g. loan",
    allowWordsTitle = "Allowed words",
    allowWordsHint = "A notification containing this word is never hidden.",
    allowWordsPlaceholder = "e.g. revolut",
    add = "Add",
    remove = "Remove",
    emptyList = "Empty",
    wordMatchHint = "Words match from the start: “loan” catches “loans”, but not inside another word.",

    callsTitle = "Calls",
    silenceUnknown = "Silence unknown numbers",
    silenceUnknownHint = "Calls outside your contacts ring silently but still appear in the call log",
    callsWarning = "Assign this app for call screening, otherwise the setting does nothing",

    appearanceTitle = "Appearance",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    langSystem = "System",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Privacy",
    storeText = "Keep text in the log",
    storeTextHint = "Turn off if you don't want notification text stored on the device",

    openLog = "Log",
    openLogHint = "Hidden notifications and silenced calls",
    tabNotifications = "Notifications",
    tabCalls = "Calls",
    clear = "Clear",
    emptyNotifications = "Nothing hidden yet",
    emptyCalls = "No silenced calls yet",
    unwhitelist = "Stop hiding this app",
    hiddenText = "text not stored",
    silenced = "silenced",
    allowedCall = "rang normally",

    pickerTitle = "Always show",
    pickerHint = "The list fills up as apps send notifications",
    pickerEmpty = "Apps appear here after their first notification",
    search = "Search",
    done = "Done"
)

val LocalStrings = staticCompositionLocalOf { RU }
