package com.guard.notifyguard

import androidx.compose.runtime.staticCompositionLocalOf

enum class Lang { SYSTEM, RU, EN }

data class Strings(
    val appTitle: String,
    val logTitle: String,
    val dictTitle: String,
    val back: String,

    val accessTitle: String,
    val accessNotifications: String,
    val accessNotificationsOn: String,
    val accessNotificationsOff: String,
    val accessCalls: String,
    val accessCallsOn: String,
    val accessCallsOff: String,
    val accessContacts: String,
    val accessContactsOn: String,
    val accessContactsOff: String,
    val actionOpenSettings: String,
    val actionAssign: String,
    val actionGrant: String,
    val enabled: String,
    val disabled: String,

    val notificationsTitle: String,
    val hideAds: String,
    val hideAdsHint: String,
    val strictMode: String,
    val strictModeHint: String,
    val whitelistCount: String,
    val chooseApps: String,

    val openDict: String,
    val openDictHint: String,
    val openLog: String,
    val openLogHint: String,

    val tabStop: String,
    val tabAllow: String,
    val tabBuiltIn: String,
    val stopWordsHint: String,
    val stopWordsPlaceholder: String,
    val allowWordsHint: String,
    val allowWordsPlaceholder: String,
    val builtInHint: String,
    val add: String,
    val remove: String,
    val emptyList: String,
    val wordMatchHint: String,
    val wordsCount: String,

    val groupPromo: String,
    val groupCode: String,
    val groupMoney: String,
    val groupDelivery: String,
    val groupSystem: String,
    val groupEmergency: String,

    val callsTitle: String,
    val silenceUnknown: String,
    val silenceUnknownHint: String,
    val callsWarning: String,

    val appearanceTitle: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val langSystem: String,
    val langRu: String,
    val langEn: String,

    val privacyTitle: String,
    val storeText: String,
    val storeTextHint: String,

    val updateTitle: String,
    val updateAuto: String,
    val updateAutoHint: String,
    val updateCheck: String,
    val updateChecking: String,
    val updateUpToDate: String,
    val updateFound: String,
    val updateDownload: String,
    val updateDownloading: String,
    val updateInstall: String,
    val updateFailed: String,
    val updateNeedPermission: String,
    val updateGrant: String,
    val currentVersion: String,
    val updateNetworkNote: String,

    val tabNotifications: String,
    val tabCalls: String,
    val clear: String,
    val emptyNotifications: String,
    val emptyCalls: String,
    val unwhitelist: String,
    val hiddenText: String,
    val silenced: String,

    val pickerTitle: String,
    val pickerHint: String,
    val pickerEmpty: String,
    val search: String,
    val done: String,
    val cancel: String
)

val RU = Strings(
    appTitle = "Тихие уведомления",
    logTitle = "Журнал",
    dictTitle = "Словарь",
    back = "Назад",

    accessTitle = "Доступ",
    accessNotifications = "Чтение уведомлений",
    accessNotificationsOn = "Фильтр может снимать уведомления",
    accessNotificationsOff = "Без этого доступа фильтр не работает",
    accessCalls = "Проверка звонков",
    accessCallsOn = "Можно приглушать незнакомые номера",
    accessCallsOff = "Нужно, чтобы приглушать звонки",
    accessContacts = "Доступ к контактам",
    accessContactsOn = "Знакомые номера звонят как обычно",
    accessContactsOff = "Без контактов все номера считаются знакомыми",
    actionOpenSettings = "Настройки",
    actionAssign = "Назначить",
    actionGrant = "Разрешить",
    enabled = "включено",
    disabled = "выключено",

    notificationsTitle = "Уведомления",
    hideAds = "Скрывать рекламу",
    hideAdsHint = "Коды, операции по счёту, личные сообщения, статусы доставки и экстренные оповещения остаются",
    strictMode = "Строгий режим",
    strictModeHint = "Показывать только белый список, коды и переводы",
    whitelistCount = "Белый список",
    chooseApps = "Приложения",

    openDict = "Словарь",
    openDictHint = "Стоп-слова, исключения и встроенные списки",
    openLog = "Журнал",
    openLogHint = "Скрытые уведомления и приглушённые звонки",

    tabStop = "Стоп-слова",
    tabAllow = "Исключения",
    tabBuiltIn = "Встроенные",
    stopWordsHint = "Уведомление с таким словом скрывается, даже если в нём есть сумма или слово «код». Экстренные оповещения и состояние устройства не перекрываются.",
    stopWordsPlaceholder = "например: кредит",
    allowWordsHint = "Уведомление с таким словом не скрывается никогда.",
    allowWordsPlaceholder = "например: сбербанк",
    builtInHint = "Списки, зашитые в приложение. Их нельзя изменить, но можно перекрыть своими словами.",
    add = "Добавить",
    remove = "Удалить",
    emptyList = "Список пуст",
    wordMatchHint = "Слово ищется по началу: «кредит» поймает «кредиты», но не сработает внутри другого слова.",
    wordsCount = "слов",

    groupPromo = "Реклама",
    groupCode = "Коды подтверждения",
    groupMoney = "Операции по счёту",
    groupDelivery = "Статусы доставки",
    groupSystem = "Состояние устройства",
    groupEmergency = "Экстренные оповещения",

    callsTitle = "Звонки",
    silenceUnknown = "Приглушать незнакомые номера",
    silenceUnknownHint = "Звонок не из контактов проходит без звука, но остаётся в журнале вызовов",
    callsWarning = "Назначьте приложение для проверки звонков, иначе настройка ни на что не влияет",

    appearanceTitle = "Оформление",
    theme = "Тема",
    themeSystem = "Системная",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    language = "Язык",
    langSystem = "Системный",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Приватность",
    storeText = "Сохранять текст в журнале",
    storeTextHint = "Выключите, если не хотите, чтобы тексты уведомлений хранились на устройстве",

    updateTitle = "Обновления",
    updateAuto = "Проверять обновления",
    updateAutoHint = "Раз в сутки при открытии приложения. Запрос уходит только на api.github.com",
    updateCheck = "Проверить сейчас",
    updateChecking = "Проверяю…",
    updateUpToDate = "Установлена последняя версия",
    updateFound = "Доступна версия",
    updateDownload = "Скачать",
    updateDownloading = "Загрузка…",
    updateInstall = "Установить",
    updateFailed = "Не удалось проверить обновления",
    updateNeedPermission = "Разрешите установку приложений из этого источника",
    updateGrant = "Разрешить",
    currentVersion = "Текущая версия",
    updateNetworkNote = "Интернет используется только для проверки и загрузки обновлений. Тексты уведомлений никуда не отправляются.",

    tabNotifications = "Уведомления",
    tabCalls = "Звонки",
    clear = "Очистить",
    emptyNotifications = "Пока ничего не скрыто",
    emptyCalls = "Приглушённых звонков не было",
    unwhitelist = "Больше не скрывать это приложение",
    hiddenText = "текст не сохранён",
    silenced = "приглушён",

    pickerTitle = "Всегда показывать",
    pickerHint = "Список пополняется по мере того, как приложения присылают уведомления",
    pickerEmpty = "Приложения появятся здесь после первых уведомлений",
    search = "Поиск",
    done = "Готово",
    cancel = "Отмена"
)

val EN = Strings(
    appTitle = "Quiet Notifications",
    logTitle = "Log",
    dictTitle = "Dictionary",
    back = "Back",

    accessTitle = "Access",
    accessNotifications = "Notification access",
    accessNotificationsOn = "The filter can dismiss notifications",
    accessNotificationsOff = "The filter does nothing without this",
    accessCalls = "Call screening",
    accessCallsOn = "Unknown numbers can be silenced",
    accessCallsOff = "Required to silence calls",
    accessContacts = "Contacts access",
    accessContactsOn = "Known numbers ring normally",
    accessContactsOff = "Without contacts every number counts as known",
    actionOpenSettings = "Settings",
    actionAssign = "Assign",
    actionGrant = "Grant",
    enabled = "on",
    disabled = "off",

    notificationsTitle = "Notifications",
    hideAds = "Hide ads",
    hideAdsHint = "Codes, account activity, personal messages, delivery updates and emergency alerts stay visible",
    strictMode = "Strict mode",
    strictModeHint = "Show only whitelisted apps, codes and transfers",
    whitelistCount = "Whitelist",
    chooseApps = "Apps",

    openDict = "Dictionary",
    openDictHint = "Blocked words, exceptions and built-in lists",
    openLog = "Log",
    openLogHint = "Hidden notifications and silenced calls",

    tabStop = "Blocked",
    tabAllow = "Allowed",
    tabBuiltIn = "Built-in",
    stopWordsHint = "A notification containing this word is hidden even if it mentions an amount or a code. Emergency alerts and device status are never overridden.",
    stopWordsPlaceholder = "e.g. loan",
    allowWordsHint = "A notification containing this word is never hidden.",
    allowWordsPlaceholder = "e.g. revolut",
    builtInHint = "Lists bundled with the app. They can't be edited, but your own words take priority.",
    add = "Add",
    remove = "Remove",
    emptyList = "Empty",
    wordMatchHint = "Words match from the start: “loan” catches “loans”, but not inside another word.",
    wordsCount = "words",

    groupPromo = "Advertising",
    groupCode = "Verification codes",
    groupMoney = "Account activity",
    groupDelivery = "Delivery updates",
    groupSystem = "Device status",
    groupEmergency = "Emergency alerts",

    callsTitle = "Calls",
    silenceUnknown = "Silence unknown numbers",
    silenceUnknownHint = "Calls outside your contacts ring silently but still appear in the call log",
    callsWarning = "Assign this app for call screening, otherwise the setting does nothing",

    appearanceTitle = "Appearance",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    langSystem = "System",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Privacy",
    storeText = "Keep text in the log",
    storeTextHint = "Turn off if you don't want notification text stored on the device",

    updateTitle = "Updates",
    updateAuto = "Check for updates",
    updateAutoHint = "Once a day when you open the app. Only api.github.com is contacted",
    updateCheck = "Check now",
    updateChecking = "Checking…",
    updateUpToDate = "You're on the latest version",
    updateFound = "Version available",
    updateDownload = "Download",
    updateDownloading = "Downloading…",
    updateInstall = "Install",
    updateFailed = "Couldn't check for updates",
    updateNeedPermission = "Allow installing apps from this source",
    updateGrant = "Allow",
    currentVersion = "Current version",
    updateNetworkNote = "The network is used only to check and download updates. Notification text is never sent anywhere.",

    tabNotifications = "Notifications",
    tabCalls = "Calls",
    clear = "Clear",
    emptyNotifications = "Nothing hidden yet",
    emptyCalls = "No silenced calls yet",
    unwhitelist = "Stop hiding this app",
    hiddenText = "text not stored",
    silenced = "silenced",

    pickerTitle = "Always show",
    pickerHint = "The list fills up as apps send notifications",
    pickerEmpty = "Apps appear here after their first notification",
    search = "Search",
    done = "Done",
    cancel = "Cancel"
)

val LocalStrings = staticCompositionLocalOf { RU }
