package com.guard.notifyguard

import androidx.compose.runtime.staticCompositionLocalOf

enum class Lang { SYSTEM, RU, EN }

data class Strings(
    val appTitle: String,
    val logTitle: String,
    val dictTitle: String,
    val back: String,

    val accessTitle: String,
    val accessNotifications: String,
    val accessNotificationsOn: String,
    val accessNotificationsOff: String,
    val accessCalls: String,
    val accessCallsOn: String,
    val accessCallsOff: String,
    val accessContacts: String,
    val accessContactsOn: String,
    val accessContactsOff: String,
    val actionOpenSettings: String,
    val actionAssign: String,
    val actionGrant: String,
    val enabled: String,
    val disabled: String,

    val notificationsTitle: String,
    val hideAds: String,
    val hideAdsHint: String,
    val strictMode: String,
    val strictModeHint: String,
    val whitelistCount: String,
    val chooseApps: String,

    val openDict: String,
    val openDictHint: String,
    val openLog: String,
    val openLogHint: String,

    val tabMine: String,
    val tabReady: String,
    val modeBlock: String,
    val modeAllow: String,
    val tabBuiltIn: String,
    val tabOnline: String,
    val onlineTitle: String,
    val onlineHint: String,
    val onlineEnabled: String,
    val onlineEnabledHint: String,
    val onlineVersion: String,
    val onlineUpdated: String,
    val onlineNever: String,
    val onlineSync: String,
    val onlineSyncing: String,
    val onlineFailed: String,
    val onlineBlocked: String,
    val onlineAllowed: String,
    val onlineSafety: String,
    val stopWordsHint: String,
    val stopWordsPlaceholder: String,
    val allowWordsHint: String,
    val allowWordsPlaceholder: String,
    val builtInHint: String,
    val add: String,
    val remove: String,
    val emptyList: String,
    val wordMatchHint: String,
    val wordsCount: String,

    val groupPromo: String,
    val groupCode: String,
    val groupMoney: String,
    val groupDelivery: String,
    val groupSystem: String,
    val groupEmergency: String,

    val callsTitle: String,
    val silenceUnknown: String,
    val silenceUnknownHint: String,
    val callsWarning: String,

    val appearanceTitle: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val langSystem: String,
    val langRu: String,
    val langEn: String,

    val privacyTitle: String,
    val storeText: String,
    val storeTextHint: String,

    val updateTitle: String,
    val updateAuto: String,
    val updateAutoHint: String,
    val updateCheck: String,
    val updateChecking: String,
    val updateUpToDate: String,
    val updateFound: String,
    val updateDownload: String,
    val updateDownloading: String,
    val updateInstall: String,
    val updateFailed: String,
    val updateNeedPermission: String,
    val updateGrant: String,
    val currentVersion: String,
    val updateNetworkNote: String,

    val tabNotifications: String,
    val tabCalls: String,
    val clear: String,
    val emptyNotifications: String,
    val emptyCalls: String,
    val unwhitelist: String,
    val hiddenText: String,
    val silenced: String,

    val pickerTitle: String,
    val pickerHint: String,
    val pickerEmpty: String,
    val search: String,
    val done: String,
    val cancel: String,

    val navProtect: String,
    val navDict: String,
    val navLog: String,
    val navHelp: String,

    val setupTitle: String,
    val setupIntro: String,
    val setupStep1: String,
    val setupStep1Text: String,
    val setupStep2: String,
    val setupStep2Text: String,
    val setupStep3: String,
    val setupStep3Text: String,
    val setupRestricted: String,
    val setupRestrictedText: String,
    val setupHide: String,
    val setupShow: String,
    val setupSkip: String,
    val setupDone: String,

    val numberTitle: String,
    val numberKind: String,
    val numberCountry: String,
    val numberRegion: String,
    val numberOperator: String,
    val numberRisk: String,
    val riskLow: String,
    val riskMedium: String,
    val riskHigh: String,
    val riskUnknown: String,
    val kindMobile: String,
    val kindLandline: String,
    val kindTollFree: String,
    val kindPremium: String,
    val kindShort: String,
    val kindHidden: String,
    val kindForeign: String,
    val kindUnknown: String,
    val sigPremium: String,
    val sigTollFree: String,
    val sigLandline: String,
    val sigForeign: String,
    val sigRepeated: String,
    val sigBlockCalling: String,
    val sigLength: String,
    val sigHidden: String,
    val sigShort: String,
    val numberDisclaimer: String,
    val numberCheckOnline: String,
    val numberCheckWarning: String,
    val numberAddContact: String,

    val feedbackTitle: String,
    val feedbackHint: String,
    val feedbackKindBug: String,
    val feedbackKindIdea: String,
    val feedbackPlaceholder: String,
    val feedbackSend: String,
    val feedbackCopy: String,
    val feedbackCopied: String,
    val feedbackInclude: String,
    val feedbackIncludeHint: String,
    val feedbackNote: String,
    val feedbackNoBrowser: String,

    val welcomeTitle: String,
    val welcomeText: String,
    val regionTitle: String,
    val regionHint: String,
    val regionRu: String,
    val regionRuHint: String,
    val regionEn: String,
    val regionEnHint: String,
    val regionAll: String,
    val regionAllHint: String,
    val regionNote: String,
    val continueBtn: String,
    val groupPromoRegion: String
)

val RU = Strings(
    appTitle = "Тихие уведомления",
    logTitle = "Журнал",
    dictTitle = "Словарь",
    back = "Назад",

    accessTitle = "Доступ",
    accessNotifications = "Чтение уведомлений",
    accessNotificationsOn = "Фильтр может снимать уведомления",
    accessNotificationsOff = "Без этого доступа фильтр не работает",
    accessCalls = "Проверка звонков",
    accessCallsOn = "Можно приглушать незнакомые номера",
    accessCallsOff = "Нужно, чтобы приглушать звонки",
    accessContacts = "Доступ к контактам",
    accessContactsOn = "Знакомые номера звонят как обычно",
    accessContactsOff = "Без контактов все номера считаются знакомыми",
    actionOpenSettings = "Настройки",
    actionAssign = "Назначить",
    actionGrant = "Разрешить",
    enabled = "включено",
    disabled = "выключено",

    notificationsTitle = "Уведомления",
    hideAds = "Скрывать рекламу",
    hideAdsHint = "Коды, операции по счёту, личные сообщения, статусы доставки и экстренные оповещения остаются",
    strictMode = "Строгий режим",
    strictModeHint = "Показывать только белый список, коды и переводы",
    whitelistCount = "Белый список",
    chooseApps = "Приложения",

    openDict = "Словарь",
    openDictHint = "Стоп-слова, исключения и встроенные списки",
    openLog = "Журнал",
    openLogHint = "Скрытые уведомления и приглушённые звонки",

    tabMine = "Мои слова",
    tabReady = "Готовые",
    modeBlock = "Скрывать",
    modeAllow = "Показывать",
    tabBuiltIn = "Встроенные",
    tabOnline = "Онлайн",
    onlineTitle = "Онлайн-словарь",
    onlineHint = "Общий список слов из репозитория приложения. Обновляется раз в сутки, без переустановки.",
    onlineEnabled = "Использовать онлайн-словарь",
    onlineEnabledHint = "Выключите, если хотите полагаться только на встроенные и свои списки",
    onlineVersion = "Версия словаря",
    onlineUpdated = "Обновлён",
    onlineNever = "ещё не загружался",
    onlineSync = "Обновить сейчас",
    onlineSyncing = "Загружаю…",
    onlineFailed = "Не удалось загрузить словарь",
    onlineBlocked = "рекламных слов",
    onlineAllowed = "исключений",
    onlineSafety = "Онлайн-словарь может только добавлять рекламные слова. Экстренные оповещения, коды подтверждения, операции по счёту и ваши личные списки он перекрыть не может.",
    stopWordsHint = "Уведомление с таким словом скрывается, даже если в нём есть сумма или слово «код». Экстренные оповещения и состояние устройства не перекрываются.",
    stopWordsPlaceholder = "например: кредит",
    allowWordsHint = "Уведомление с таким словом не скрывается никогда.",
    allowWordsPlaceholder = "например: сбербанк",
    builtInHint = "Списки, зашитые в приложение. Их нельзя изменить, но можно перекрыть своими словами.",
    add = "Добавить",
    remove = "Удалить",
    emptyList = "Список пуст",
    wordMatchHint = "Слово ищется по началу: «кредит» поймает «кредиты», но не сработает внутри другого слова.",
    wordsCount = "слов",

    groupPromo = "Реклама",
    groupCode = "Коды подтверждения",
    groupMoney = "Операции по счёту",
    groupDelivery = "Статусы доставки",
    groupSystem = "Состояние устройства",
    groupEmergency = "Экстренные оповещения",

    callsTitle = "Звонки",
    silenceUnknown = "Приглушать незнакомые номера",
    silenceUnknownHint = "Звонок не из контактов проходит без звука, но остаётся в журнале вызовов",
    callsWarning = "Назначьте приложение для проверки звонков, иначе настройка ни на что не влияет",

    appearanceTitle = "Оформление",
    theme = "Тема",
    themeSystem = "Системная",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    language = "Язык",
    langSystem = "Системный",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Приватность",
    storeText = "Сохранять текст в журнале",
    storeTextHint = "Выключите, если не хотите, чтобы тексты уведомлений хранились на устройстве",

    updateTitle = "Обновления",
    updateAuto = "Проверять обновления",
    updateAutoHint = "Раз в сутки при открытии приложения. Запрос уходит только на api.github.com",
    updateCheck = "Проверить сейчас",
    updateChecking = "Проверяю…",
    updateUpToDate = "Установлена последняя версия",
    updateFound = "Доступна версия",
    updateDownload = "Скачать",
    updateDownloading = "Загрузка…",
    updateInstall = "Установить",
    updateFailed = "Не удалось проверить обновления",
    updateNeedPermission = "Разрешите установку приложений из этого источника",
    updateGrant = "Разрешить",
    currentVersion = "Текущая версия",
    updateNetworkNote = "Интернет используется только для проверки и загрузки обновлений. Тексты уведомлений никуда не отправляются.",

    tabNotifications = "Уведомления",
    tabCalls = "Звонки",
    clear = "Очистить",
    emptyNotifications = "Пока ничего не скрыто",
    emptyCalls = "Приглушённых звонков не было",
    unwhitelist = "Больше не скрывать это приложение",
    hiddenText = "текст не сохранён",
    silenced = "приглушён",

    pickerTitle = "Всегда показывать",
    pickerHint = "Список пополняется по мере того, как приложения присылают уведомления",
    pickerEmpty = "Приложения появятся здесь после первых уведомлений",
    search = "Поиск",
    done = "Готово",
    cancel = "Отмена",

    navProtect = "Защита",
    navDict = "Словарь",
    navLog = "Журнал",
    navHelp = "Справка",

    setupTitle = "Настройка",
    setupIntro = "Три шага, после которых приложение начнёт работать. Инструкцию можно скрыть — она останется в разделе «Справка».",
    setupStep1 = "Разрешите чтение уведомлений",
    setupStep1Text = "Без этого фильтр не увидит ни одного уведомления и не сможет ничего скрыть. Нажмите кнопку, найдите приложение в списке и включите переключатель.",
    setupStep2 = "Дайте доступ к контактам",
    setupStep2Text = "Нужен, чтобы отличать знакомые номера от незнакомых. Без него все звонки считаются знакомыми и ничего не приглушается.",
    setupStep3 = "Назначьте приложение для проверки звонков",
    setupStep3Text = "Только так можно приглушать незнакомые номера. Учтите: роль на телефоне одна, встроенный определитель номера перестанет работать.",
    setupRestricted = "Переключатель неактивен?",
    setupRestrictedText = "Android блокирует такие настройки для приложений, установленных файлом. Откройте Настройки → Приложения → Тихие уведомления → три точки вверху → «Разрешить ограниченные настройки», затем вернитесь.",
    setupHide = "Скрыть инструкцию",
    setupShow = "Показать инструкцию",
    setupSkip = "Пропустить",
    setupDone = "Всё настроено",

    numberTitle = "О номере",
    numberKind = "Тип",
    numberCountry = "Страна",
    numberRegion = "Регион",
    numberOperator = "Оператор",
    numberRisk = "Оценка",
    riskLow = "Признаков обзвона нет",
    riskMedium = "Есть настораживающие признаки",
    riskHigh = "Похоже на массовый обзвон",
    riskUnknown = "Недостаточно данных",
    kindMobile = "мобильный",
    kindLandline = "городской",
    kindTollFree = "бесплатный 8-800",
    kindPremium = "платный вызов",
    kindShort = "короткий номер",
    kindHidden = "скрытый номер",
    kindForeign = "зарубежный",
    kindUnknown = "не определён",
    sigPremium = "Префикс 809 — вызов платный, частый приём мошенников",
    sigTollFree = "Номер 8-800 обычно принадлежит организации",
    sigLandline = "Городской номер с определяемым регионом",
    sigForeign = "Зарубежный номер",
    sigRepeated = "С этого номера уже звонили несколько раз",
    sigBlockCalling = "С соседних номеров того же диапазона были звонки — признак колл-центра",
    sigLength = "Необычная длина номера",
    sigHidden = "Номер не определился",
    sigShort = "Короткий сервисный номер",
    numberDisclaimer = "Оценка построена на нумерации и на истории звонков этого телефона. Это подсказка, а не проверка по базе мошенников.",
    numberCheckOnline = "Проверить в открытых справочниках",
    numberCheckWarning = "Откроется браузер, номер станет виден стороннему сайту.",
    numberAddContact = "Номер знакомый? Добавьте его в контакты, и звонки перестанут приглушаться.",

    feedbackTitle = "Обратная связь",
    feedbackHint = "Опишите проблему или предложение. Откроется страница GitHub с уже заполненной формой — отправите её сами, под своей учётной записью.",
    feedbackKindBug = "Ошибка",
    feedbackKindIdea = "Предложение",
    feedbackPlaceholder = "Что случилось или что предложить",
    feedbackSend = "Открыть форму",
    feedbackCopy = "Скопировать текст",
    feedbackCopied = "Текст скопирован",
    feedbackInclude = "Приложить версию и модель",
    feedbackIncludeHint = "Версия приложения, версия Android, модель телефона. Без этого разобраться в ошибке сложнее",
    feedbackNote = "Приложение ничего не отправляет само: отправка происходит в браузере, вашими руками. Для этого нужна учётная запись GitHub.",
    feedbackNoBrowser = "Не удалось открыть браузер — текст скопирован",

    welcomeTitle = "Тихие уведомления",
    welcomeText = "Приложение скрывает рекламные уведомления и приглушает звонки с незнакомых номеров. Начнём с одного вопроса.",
    regionTitle = "Язык рекламы",
    regionHint = "На каком языке вам приходят рекламные рассылки? Это влияет только на список рекламных слов.",
    regionRu = "Русский",
    regionRuHint = "Скидки, промокоды, кредиты, маркетплейсы",
    regionEn = "English / Deutsch",
    regionEnHint = "Sales, coupons, loans, marketplaces",
    regionAll = "Оба",
    regionAllHint = "Полный словарь, если рассылки приходят на двух языках",
    regionNote = "Коды подтверждения, банковские операции, статусы доставки и экстренные оповещения распознаются на всех языках независимо от выбора. Поменять можно в любой момент.",
    continueBtn = "Продолжить",
    groupPromoRegion = "Реклама (ваш регион)"
)

val EN = Strings(
    appTitle = "Quiet Notifications",
    logTitle = "Log",
    dictTitle = "Dictionary",
    back = "Back",

    accessTitle = "Access",
    accessNotifications = "Notification access",
    accessNotificationsOn = "The filter can dismiss notifications",
    accessNotificationsOff = "The filter does nothing without this",
    accessCalls = "Call screening",
    accessCallsOn = "Unknown numbers can be silenced",
    accessCallsOff = "Required to silence calls",
    accessContacts = "Contacts access",
    accessContactsOn = "Known numbers ring normally",
    accessContactsOff = "Without contacts every number counts as known",
    actionOpenSettings = "Settings",
    actionAssign = "Assign",
    actionGrant = "Grant",
    enabled = "on",
    disabled = "off",

    notificationsTitle = "Notifications",
    hideAds = "Hide ads",
    hideAdsHint = "Codes, account activity, personal messages, delivery updates and emergency alerts stay visible",
    strictMode = "Strict mode",
    strictModeHint = "Show only whitelisted apps, codes and transfers",
    whitelistCount = "Whitelist",
    chooseApps = "Apps",

    openDict = "Dictionary",
    openDictHint = "Blocked words, exceptions and built-in lists",
    openLog = "Log",
    openLogHint = "Hidden notifications and silenced calls",

    tabMine = "My words",
    tabReady = "Bundled",
    modeBlock = "Hide",
    modeAllow = "Show",
    tabBuiltIn = "Built-in",
    tabOnline = "Online",
    onlineTitle = "Online dictionary",
    onlineHint = "Shared word list from the app repository. Refreshed daily, no reinstall needed.",
    onlineEnabled = "Use online dictionary",
    onlineEnabledHint = "Turn off to rely only on built-in and your own lists",
    onlineVersion = "Dictionary version",
    onlineUpdated = "Updated",
    onlineNever = "never fetched",
    onlineSync = "Refresh now",
    onlineSyncing = "Loading…",
    onlineFailed = "Couldn't load the dictionary",
    onlineBlocked = "ad words",
    onlineAllowed = "exceptions",
    onlineSafety = "The online dictionary can only add ad words. It cannot override emergency alerts, verification codes, account activity or your own lists.",
    stopWordsHint = "A notification containing this word is hidden even if it mentions an amount or a code. Emergency alerts and device status are never overridden.",
    stopWordsPlaceholder = "e.g. loan",
    allowWordsHint = "A notification containing this word is never hidden.",
    allowWordsPlaceholder = "e.g. revolut",
    builtInHint = "Lists bundled with the app. They can't be edited, but your own words take priority.",
    add = "Add",
    remove = "Remove",
    emptyList = "Empty",
    wordMatchHint = "Words match from the start: “loan” catches “loans”, but not inside another word.",
    wordsCount = "words",

    groupPromo = "Advertising",
    groupCode = "Verification codes",
    groupMoney = "Account activity",
    groupDelivery = "Delivery updates",
    groupSystem = "Device status",
    groupEmergency = "Emergency alerts",

    callsTitle = "Calls",
    silenceUnknown = "Silence unknown numbers",
    silenceUnknownHint = "Calls outside your contacts ring silently but still appear in the call log",
    callsWarning = "Assign this app for call screening, otherwise the setting does nothing",

    appearanceTitle = "Appearance",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    langSystem = "System",
    langRu = "Русский",
    langEn = "English",

    privacyTitle = "Privacy",
    storeText = "Keep text in the log",
    storeTextHint = "Turn off if you don't want notification text stored on the device",

    updateTitle = "Updates",
    updateAuto = "Check for updates",
    updateAutoHint = "Once a day when you open the app. Only api.github.com is contacted",
    updateCheck = "Check now",
    updateChecking = "Checking…",
    updateUpToDate = "You're on the latest version",
    updateFound = "Version available",
    updateDownload = "Download",
    updateDownloading = "Downloading…",
    updateInstall = "Install",
    updateFailed = "Couldn't check for updates",
    updateNeedPermission = "Allow installing apps from this source",
    updateGrant = "Allow",
    currentVersion = "Current version",
    updateNetworkNote = "The network is used only to check and download updates. Notification text is never sent anywhere.",

    tabNotifications = "Notifications",
    tabCalls = "Calls",
    clear = "Clear",
    emptyNotifications = "Nothing hidden yet",
    emptyCalls = "No silenced calls yet",
    unwhitelist = "Stop hiding this app",
    hiddenText = "text not stored",
    silenced = "silenced",

    pickerTitle = "Always show",
    pickerHint = "The list fills up as apps send notifications",
    pickerEmpty = "Apps appear here after their first notification",
    search = "Search",
    done = "Done",
    cancel = "Cancel",

    navProtect = "Guard",
    navDict = "Words",
    navLog = "Log",
    navHelp = "Help",

    setupTitle = "Setup",
    setupIntro = "Three steps and the app starts working. You can hide this guide — it stays in the Help tab.",
    setupStep1 = "Allow notification access",
    setupStep1Text = "Without it the filter sees no notifications at all. Tap the button, find the app in the list and turn the switch on.",
    setupStep2 = "Grant contacts access",
    setupStep2Text = "Needed to tell known numbers from unknown ones. Without it every caller counts as known and nothing is silenced.",
    setupStep3 = "Assign call screening",
    setupStep3Text = "The only way to silence unknown numbers. Note: this role is exclusive, your built-in caller ID will stop working.",
    setupRestricted = "Switch greyed out?",
    setupRestrictedText = "Android restricts these settings for sideloaded apps. Open Settings → Apps → Quiet Notifications → three dots → “Allow restricted settings”, then come back.",
    setupHide = "Hide guide",
    setupShow = "Show guide",
    setupSkip = "Skip",
    setupDone = "All set",

    numberTitle = "About this number",
    numberKind = "Type",
    numberCountry = "Country",
    numberRegion = "Region",
    numberOperator = "Carrier",
    numberRisk = "Assessment",
    riskLow = "No signs of mass calling",
    riskMedium = "Some warning signs",
    riskHigh = "Looks like mass calling",
    riskUnknown = "Not enough data",
    kindMobile = "mobile",
    kindLandline = "landline",
    kindTollFree = "toll-free",
    kindPremium = "premium rate",
    kindShort = "short code",
    kindHidden = "withheld",
    kindForeign = "international",
    kindUnknown = "unknown",
    sigPremium = "Premium-rate prefix — the call itself costs money, a common scam",
    sigTollFree = "Toll-free numbers usually belong to a company",
    sigLandline = "Landline with an identifiable area",
    sigForeign = "International number",
    sigRepeated = "This number has called several times already",
    sigBlockCalling = "Neighbouring numbers in the same range also called — typical of a call centre",
    sigLength = "Unusual number length",
    sigHidden = "Caller ID withheld",
    sigShort = "Short service number",
    numberDisclaimer = "The assessment is based on numbering rules and this phone's own call history. It is a hint, not a check against a fraud database.",
    numberCheckOnline = "Look up in public directories",
    numberCheckWarning = "Opens a browser; the number becomes visible to a third-party site.",
    numberAddContact = "Know this number? Add it to contacts and calls will ring normally.",

    feedbackTitle = "Feedback",
    feedbackHint = "Describe a problem or an idea. A GitHub page opens with the form pre-filled — you send it yourself, from your own account.",
    feedbackKindBug = "Bug",
    feedbackKindIdea = "Idea",
    feedbackPlaceholder = "What happened, or what you suggest",
    feedbackSend = "Open the form",
    feedbackCopy = "Copy text",
    feedbackCopied = "Copied",
    feedbackInclude = "Attach version and device",
    feedbackIncludeHint = "App version, Android version, phone model. Harder to debug without it",
    feedbackNote = "The app never sends anything by itself: submission happens in the browser, by you. A GitHub account is required.",
    feedbackNoBrowser = "Couldn't open a browser — text copied instead",

    welcomeTitle = "Quiet Notifications",
    welcomeText = "This app hides ad notifications and silences calls from numbers outside your contacts. One question first.",
    regionTitle = "Language of the ads",
    regionHint = "Which language do marketing messages reach you in? This only affects the list of advertising words.",
    regionRu = "Русский",
    regionRuHint = "Скидки, промокоды, кредиты, маркетплейсы",
    regionEn = "English / Deutsch",
    regionEnHint = "Sales, coupons, loans, marketplaces",
    regionAll = "Both",
    regionAllHint = "The full dictionary, if you get marketing in both languages",
    regionNote = "Verification codes, bank activity, delivery updates and emergency alerts are recognised in every language regardless of this choice. You can change it any time.",
    continueBtn = "Continue",
    groupPromoRegion = "Advertising (your region)"
)

val LocalStrings = staticCompositionLocalOf { RU }
